name: Build and Push Database Exporter

on:
  push:
    branch:
      - ekw/gh-actions/release

env:
  UBUNTU_VERSION: '22.04'
  RUST_IMAGE_TAG: '1.73.0'
  EUR2CCD_VERSION: '0.6.1'
  BUILD_VERSION: '20'
  S3_BUCKET: 's3://eur2ccd.concordium.com'

jobs:
  release-euro2ccd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.EUR2CCD_VERSION }}
          submodules: recursive

      - name: Build
        run: |
          docker build -t ccd-service-builder --build-arg ubuntu_version=${{ env.UBUNTU_VERSION }} --build-arg rust_image_tag=${{ env.RUST_IMAGE_TAG }} -f scripts/debian-package/deb.Dockerfile .
          set -euxo pipefail
          id=$(docker create ccd-service-builder)
          docker cp $id:/build/pkg-root/ eur2ccd-deb
          docker rm $id
          mv eur2ccd-deb/concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb .

      - name: Publish
        run: |
          aws s3 cp concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb "${{ env.S3_Bucket }}/concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}-${{ env.BUILD_VERSION }}_amd64.deb"
