name: Build and Push Database Exporter

on:
  push:
    branches:
      - ekw/gh-actions/release

env:
  UBUNTU_VERSION: '22.04'
  RUST_IMAGE_TAG: '1.73.0'
  EUR2CCD_VERSION: '0.6.1'
  BUILD_VERSION: 'test'
  S3_BUCKET: s3://eur2ccd.concordium.com

permissions:
  id-token: write
  contents: read

jobs:
  release-euro2ccd:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.EUR2CCD_VERSION }}-0
          submodules: recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-to-assume: "arn:aws:iam::192549843005:role/github-eur2ccd"
          role-session-name: ReleaseEur2ccdSession

      - name: Check built packages
        run: |
          echo S3_OBJ=$(aws s3 ls s3://eur2ccd.concordium.com/concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}-${{ env.BUILD_VERSION }}_amd64.deb) >> $GITHUB_ENV

      - name: Build
        if: ${{ env.S3_OBJ == '' }}
        run: |
          docker build -t ccd-service-builder --build-arg ubuntu_version=${{ env.UBUNTU_VERSION }} --build-arg rust_image_tag=${{ env.RUST_IMAGE_TAG }} -f scripts/debian-package/deb.Dockerfile .
          set -euxo pipefail
          id=$(docker create ccd-service-builder)
          docker cp $id:/build/pkg-root/ eur2ccd-deb
          docker rm $id
          mv eur2ccd-deb/concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb .

      - name: Publish
        if: ${{ env.S3_OBJ == '' }}
        run: |
          aws s3 cp concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}_amd64.deb s3://eur2ccd.concordium.com/concordium-eur2ccd_${{ env.EUR2CCD_VERSION }}-${{ env.BUILD_VERSION }}_amd64.deb
